alias rebuild='python3 _script/build_corex.py'
alias build_all='python3 _script/build_dependency.py; python3 _script/build_corex.py'
alias build_all_release='python3 _script/build_dependency.py -r;python3 _script/build_corex.py -r'
alias qb='python3 _script/clean_install.py; cmake --build _corex_build -- install'
alias rb='rebuild -j 24'
